//auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

//cart
export const TOGGLE_CART = 'TOGGLE_CART';
export const ADD_ITEM_CART = 'ADD_ITEM_CART';
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';
export const REMOVE_ITEM_CHECKOUT = 'REMOVE_ITEM_CHECKOUT';
